### ISSUE TITLE
Support non-UTF-8 encodings on resp

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#362]
```
error: Error: Unknown encoding
    at Buffer.toString (buffer.js:430:13)
    at /Users/subrah/dev/ql.io-public/modules/engine/lib/engine/source/verb.js:56:24
    at Array.forEach (native)
    at Function.<anonymous> (/Users/subrah/dev/ql.io-public/modules/engine/node_modules/underscore/underscore.js:76:11)
    at Object.parse response (/Users/subrah/dev/ql.io-public/modules/engine/lib/engine/source/verb.js:55:11)
```

node's buffer.js can only deal with utf-8, ascii, binary, base64, and ucs-2 encodings. We need to use iconv to deal with encodings like ISO-8859-1 on responses.

**Comment by s3u** [comment]
Potential fix

```
// check the cost of this for supported encodings like ucs-2, ascii and utf-8.
var Iconv  = require('iconv').Iconv
var iconv = new Iconv('UTF-8', encoding);
_.each(args.body, function(buf) {
    buf = (iconv.convert(buf));
    str += buf.toString('UTF-8');
});
```

**Comment by idralyuk** [comment]
Takes around 20-40 microseconds to convert to UTF-8 when encoding is provided; otherwise takes 80-100 microseconds.

Here is a representative sample from my MBP:

default 82 µs
utf8 26 µs
ucs2 23 µs
iso_8859_1 30 µs
ascii 17 µs

FYI: using https://github.com/wadey/node-microtime as the hi-resolution timer.

**Comment by idralyuk** [comment]
See https://github.com/ql-io/ql.io/pull/433
