### ISSUE TITLE
Inconsistent join behavior

### ISSUE THREAD

**Issue by mbellmbell** [ql-io/ql.io#552]
This may fall into the user error category, but I really don't understand ql.io join behavior, especially relative to RDBMS joins.  So if you look at the ql.io script here: 

http://bit.ly/UtqmEY

I have one data source that alias to two ql.io tables [I just did this as an example to make sure that my fields would match in joins].  Each table about 400 rows.

return result1: This returns the ~ 400 rows as expected

return result2: This returns 50 rows.  The join is on a unique key, so in RDBMS world I would expect that it would return the same number of rows as the original table.

return result3: This returns a very large number of rows (~ 5,500).  The element we're joining on is not unique (there are 7 distinct values in the 400 rows).  Again, with an RDBMS join I would expect that we'd get (400 \* (400/7)) = ~ 2300 or roughly half what we got back.

FWIW, my goal is to get result2 to work where we're doing a many to one join to lookup attribute data.  Any ideas?

**Comment by hochang** [comment]
Similar problem brought up by @khurrumqureshi , merge two issues together.

As per documentation http://ql.io/docs/variable-ref

resp = select \* from someDeepCollection;
ids = "{resp.$..ItemID}";
details = select \* from someDeetails where id in ("{ids}");

This script first gets the complete response of the collection, and then looks for ItemIDs. It then uses those IDs to find details. While the first statement involves a network round-trip, the second statement happens in memory.

What i understand from this is select commands run sequentially rather than parallel. but when i am doing this in my script

create table styles on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/wine_styles.json"
resultset "values";
create table wines on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/KlWines.json"
resultset "values";

t_style = select "row_values[].age_potential" as agepotential, "row_values[].adventurous" as adventurous,"row_values[].wine_style" as wineStyle,"row_values[].varietal_area" as varietal_area from styles;
t_wines = select \* from wines;
t_wineStyle=select "tw.row_values[].varietal_area" as varietal_area,s.wineStyle as wineStyle from t_wines as tw, t_style as s where "tw.row_values[].varietal_area"=s.varietal_area;

It is suppose to get result first for t_style than for t_wines and in the end for t_wineStyle but, interestingly it is not happening it get result first for t_style than for t_wines while in process it start fetching result for t_wineStyle don't wait to get t_wines finishes. Which cause to get incomplete result set means this query suppose to return 1500+ records but it returns only 33. Is it the normal behavior of ql.io or i am doing something wrong.

**Comment by hochang** [comment]
Problem is detected, please allow us some time to handle this.

**Comment by mbellmbell** [comment]
Sure, thanks... we've got a (pretty ugly) workaround for now.

**Comment by khurrumqureshi** [comment]
That's great if we have a solution for that..

**Comment by hochang** [comment]
Actually, this is not a bug. Open your config file, and in the shallowest layer of {}, put an extra line
`"maxNestedRequests" : xxxx`
where xxxx is a number that is larger than your join. Default value is 50, and that's why causing your problem.
@mmm3bbb , your script should work as expected now.
@khurrumqureshi , your script is a little bit too messy, I had smoothed it first time testing it, now I just cannot recall how. Please try with the extra line in config, and let me know if it still troubles you.

**Comment by mbellmbell** [comment]
Awesome.... will try it out.

**Comment by khurrumqureshi** [comment]
Great.. I will look at it..
