### ISSUE TITLE
How to pass params to monkey patch other than route..

### ISSUE THREAD

**Issue by khurrumqureshi** [ql-io/ql.io#555]
While looking at args passed to monkey patch there is a field params
{ uri: 
   { },
  statement: 
   { },
  params: {},
  status: 200,
  headers: 
   {},
  body: 
  {}
  log:[]
  }
I remove the data to simplify things.. No how can we pass params so it is available in args.params? does those params can be large object let's a result from any qurey and than pass as an param to monkey patch?

create table styles on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/wine_styles.json"
resultset "values";

t_style = select \* from styles

create table wines on select get from "http://api-botnik-com.herokuapp.com/v0.1/service/name/KlWines.json?startbudget={startbudget}&endbudget{endbudget}&color={color}"
using defaults startbudget=5, endbudget=30, color="red"
using patch 'services/service_WineRecommendation.js'
resultset "values";

Now in above example can i pass t_style as params to monkey patch?

**Comment by shimonchayim** [comment]
Which monkey patch? Anything you pass in the where clause should be available in the monkey patch.

**Comment by khurrumqureshi** [comment]
Let's say
select \* from wines where style=t_style

so does t_style is available to monkey patch? t_style contains a large structure as you can see in above example..

**Comment by hochang** [comment]
You don't need to use monkey patch for this use case. Instead, try to spend a little time learning insert statement http://ql.io/docs/insert, this might be what you are looking. Unfortunately, full functionality will be available in next release.

**Comment by mbellmbell** [comment]
There is more context to this and it's related to this issue: https://github.com/ql-io/ql.io/issues/552.  

We have a few tables that we're trying to join and since the joins aren't working as per the above issue, we are basically coding the "join" in a Patch Results monkey patch until the issue is resolved.  So the issue how we get the join tables into the monkey patch since we can't make network calls from within the patch.  So the hope is that we could query for join tables in the script and then pass them in as parameters to the monkey patch.  The only other way (which is what we're doing now) is to hard-code join data in monkey patch.  It works, but is a very sad thing.

**Comment by hochang** [comment]
So you still cannot join even if you make the change mentioned in #552?

**Comment by mbellmbell** [comment]
Yes, changing maxNestedRequests worked great!  It worked for joining between 2000 and 300 row tables.  There are a couple more tables that we'd also like to bring in - say 100 rows each.  Should I assume that's about (2000 \* 300 \* 100 \* 100)/2 = 3 billion comparisons?

**Comment by hochang** [comment]
Sorry for the delay, crazily busy these days. BTW, have you taken a look of update  or insert statement yet?  http://ql.io/docs/update
In this way, you can manipulate an JSON object or even a table without using monkey patch.

**Comment by shimonchayim** [comment]
Seems like we are getting a little away from the main issue. Invite participants to open a fresh issue.

**Comment by mbellmbell** [comment]
UDF assignment has eliminated the need for this.
